//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckMate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseCodeRef
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CourseCodeRef()
        {
            this.TaskDetails = new HashSet<TaskDetail>();
        }
    
        public int CourseCodeRefID { get; set; }
        public string CourseCodeName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskDetail> TaskDetails { get; set; }
    }
}
